[package]
name = "stay-awake"
version = "0.2.0"
authors = ["Curtis Alexander <calex@calex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
colored = "2.0"
structopt = "0.3"